a = int(input("Enter first number :"))
b = int(input("Enter second number :"))
print("Addition is :")
print(a+b)
print("Subtraction is :")
print(a-b)
print("Divison is :")
print(a/b)
print("Multiplication is :")
print(a*b)
print("Modual is :")
print(a%b)
