a = binary(input("Enter binary numbers :"))
b = octal(input("Enter octal numbers :"))
c = hexadecimal(input("Enter hexadecimal numbers :"))
print("Binary to decimal is :")
print(a/10)
print("octal to decimal is :")
print(b/10)
print("hexadecimal to decimal is :")
print(c/10)
